# TODO: @memes - update to match requirements
# spell-checker: disable
---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - memes
